### ISSUE TITLE
关于多号使用中控服务器的问题

### ISSUE THREAD

**Issue by xuyang404** [fastwego/offiaccount#17]
请教个问题，我的中控服务器有很多个号的access_token，我在业务中也需要多个号切换，请问这种情况下从中控服务器获取access_token的代码应该怎么写呢？

**Comment by Ceelog** [comment]
请加最新的微信开发者群 https://github.com/fastwego/fastwego.dev#%E5%BC%80%E5%8F%91%E8%80%85%E4%BA%A4%E6%B5%81%E7%BE%A4
