### ISSUE TITLE
收到POST请求缺少签名检查

### ISSUE THREAD

**Issue by rny** [fastwego/offiaccount#25]
EchoStr中进行了签名检查，但是收到POST后直接进行ParseXML了，应该先进行和EchoStr一样的签名检查，通过后再ParseXML

**Comment by citizen233** [comment]
@rny 我理解你的意思是：程序没有先去校验“消息体签名”，直接去解析密文？

**Comment by rny** [comment]
@citizen233 是request URL里面的query的签名，按照规范，无论是GET还是POST都应该先检查query里的签名是否正确，确保是微信发出给这个公众号的，然后再进行操作。

**Comment by citizen233** [comment]
![image](https://user-images.githubusercontent.com/5754261/144836377-ba2bee7a-afb1-4d3b-996b-e4164582c573.png)
是这种情况对吧？
开发的时候，默认使用这个公众号的（唯一不重复）`Token`去解密消息，解密成功就默认是微信发给这个公众号的

**Comment by rny** [comment]
ParseXML函数中如果消息是加密的就没问题，但是假如第三方伪造一个明码消息发到对应的服务器地址，因为缺少用token进行签名检查，就会被当成微信的消息进行处理了。当然，改起来很简单。我试一下pr

**Comment by rny** [comment]
pr提交了，但是我对github还不熟，没能成功的导出到本地测试，我浏览器直接改的，可能有错。
