### ISSUE TITLE
能否接入草稿箱功能？

### ISSUE THREAD

**Issue by Ansen** [fastwego/offiaccount#28]
公众平台将于2022年2月28日下线[新增永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html)和[修改永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Editing_Permanent_Rich_Media_Assets.html)。
![image](https://user-images.githubusercontent.com/676412/154395879-8d51cdba-14df-41a2-a1a5-b6f235d12b51.png)

相关文档 https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Add_draft.html

附永久图文素材接口下线后的解决办法：可参照 material 函数自行构造新接口

**Comment by citizen233** [comment]
@Ansen 可以的，我处理一下

**Comment by citizen233** [comment]
@Ansen 草稿箱部分代码，已合并

**Comment by Ansen** [comment]
> @Ansen 草稿箱部分代码，已合并

大佬辛苦
