### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by ZhangIvan** [fastwego/offiaccount#6]
我目前只看了关于发送模板消息这块代码，关于发送模板消息时，源码直接拼接access_token去请求微信服务器，一次失败后就不管了，直接抛出异常；
我觉得这样设计有点不好，原因是：
1. 可能在这个请求过程中该微信公众号被多个供应商管理，本地access-token已失效；
2. 也有可能本地请求时，正好在acces-token失效的边界值上，导致请求失败；

源码点：
https://github.com/fastwego/offiaccount/blob/master/client.go#L119

关于上述描述，都只是个人经验而言，并未采用该项目实地测试，建议在涉及acces-token请求的地方采用重试机制（retry）+刷新access-token的机制，保证请求成功的概率，微信对这块的acces-token失效有实际的错误码返回，可参考

**Comment by ZhangIvan** [comment]
我看源码中有直接封装统一post get的地方，那就可以直接处理retry机制了， 优秀！！！

https://github.com/fastwego/offiaccount/blob/master/client.go#L43
https://github.com/fastwego/offiaccount/blob/master/client.go#L60

**Comment by Ceelog** [comment]
你说的很有道理，我一开始是准备把retry的自由度留给开发者的，所以没加到框架里

**Comment by ZhangIvan** [comment]
> 你说的很有道理，我一开始是准备把retry的自由度留给开发者的，所以没加到框架里

我看你的介绍中有个功能是管理access-token中控，那可能就要权衡下2者的设计， 目前的acces-token都是这个框架在管理，开发不需要关注这点，只要直接调用就可以；

**Comment by Ceelog** [comment]
对的，有中控的话就没法加retry逻辑了，因为这是中控负责的，但是单机版还是可以考虑加一下，有时间你发个pull request ？一起review一下怎么搞比较合适

**Comment by ZhangIvan** [comment]
单击版本还是很简单的处理，您要不直接处理， 您都封装好了， 无非就是在您的HTTPGet、HTTPPost中先读一次返回，判断errcode是否为40001， 您先加急处理吧，避免其他开发者未注意该事项；我对您的中控还没了解过，只是空余时间随机拜读下您的源码，很优秀，有机会我有能力的话，会PR，感谢您的辛苦付出，谢谢

**Comment by Ceelog** [comment]
已更新到 #9

**Comment by 914795561** [comment]
> 有中控的话就没法加retry逻辑了

access-token中控的功能应该是开发者只需要实现获取access-token，而retry是在请求返回的时候做的，二者应该并不冲突吧？

**Comment by Ceelog** [comment]
已经更新retry机制了，欢迎加入开发者交流群 https://github.com/fastwego/fastwego.dev#%E5%BC%80%E5%8F%91%E8%80%85%E4%BA%A4%E6%B5%81%E7%BE%A4
